# Site settings ...
uri: domain.com
url: https://domain.com
name: Nathan Ju
title: Nathan 🚂
email: example@domain.com
author: username
baseurl: ""
keywords: "Your, Keyword, Here"
short_intro: "I'm Nathan"
description: "CS student and researcher at Illinois."
now: "A fan of abstractions, public transportation, history, the Internet, software, terse writing (working on that), and trains. 🚂"

twitter_username: nathanju34
github_username: 34ndju

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
