# Site settings ...
uri: domain.com
url: https://domain.com
name: Nathan Ju
title: Nathan Ju 🚂
email: example@domain.com
author: username
baseurl: ""
keywords: "Your, Keyword, Here"
name: "Nathan Ju"
description: "I am in the thid year of my undergraduate studies in computer science and mathematics at the University of Illinois."
now: "I am boradly interested in theoretical computer science and quantum information theory. "

twitter_username: nathanju34
github_username: 34ndju

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

remote_theme: 34ndju/mangan

defualts:
  - scope: 
        path: "assets"
        values:
        image: true
